import Head from "next/head";
import Image from "next/image";

// image
import profileImage from "../public/my6.jpg";

import design from "../public/design.png";
import code from "../public/code.png";
import con from "../public/con.png";

import auction from "../public/auction.png";
import lms from "../public/lms.png";
import train from "../public/train.png";
import cartoon from "../public/cartoon.png";
import bus from "../public/bus.jpg";
import minion from "../public/minion.png";



import { BsFillMoonStarsFill } from "react-icons/bs";

import { FaInstagramSquare } from "react-icons/fa";
import { FaGithub } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";

//hooks
import { useState } from "react";



export default function Home() {
  
  //function
  const [darkmode, setdarkmode] = useState(false);

  return (
    <div className={darkmode ? "dark" : ""}>

      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Lobster&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
        </style>
      </Head>
       
      <main className="font-poppins bg-yellow-50 px-10 md:px-20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          {/* navbar */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-xl dark:text-white">
              Developed by SANDUN SAMPATH
            </h1>
            <ul className="flex items-center">
              <li>
              <BsFillMoonStarsFill 
              className="cursor-pointer text-xl mx-5 dark:text-white"
              onClick={() => setdarkmode(!darkmode)}
              />

              </li>
              <li>
                <a href="https://drive.google.com/file/d/1h-He2PE1dul3Md-OmyW_RDIuKqQCwGXd/view?usp=sharing"

                download={"resume"}
                className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md">Resume</a>
              </li>
            </ul>
          </nav>

                  {/* hero */}
          <div className="text-center p-10">
            <h1 className="text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl">
              SANDUN SAMPATH
            </h1>
            <h3 className="text-2xl py-1 md:text-3xl dark:text-white">
            Undergraduate BSc(Hons) Software Engineering - UGC
            </h3>
            <p className="text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto md:text-md dark:text-white">
            I’m a software engineer specializing in mobile application and website development. I’m passionate about designing innovative solutions that combine user-friendly interfaces with robust functionality. I focus on creating high-quality applications and websites that meet industry standards and user needs. I’m dedicated to staying updated with emerging technologies and working collaboratively to deliver impactful software solutions.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://www.instagram.com/sandun.sampath.m/profilecard/?igsh=cDlybWtqeG5zODd3">
              <FaInstagramSquare/>
            </a>

            <a href="https://github.com/Medagangoda">
            <FaGithub/>
            </a>

            <a href="https://www.linkedin.com/in/sandun-sampath/">
            <FaLinkedin/>
            </a>
          </div>

          <div className=" m-auto relative  w-80 h-80 mt-14 rounded-full">
            <Image src={profileImage} alt="profile image" layout="fil" objectFit="cover"/>
          </div>
        </section>

        {/* services */}
        <section>
          <div>
            <h2 className="text-4xl py-6 font-bold opacity-60 dark:text-white">Services | Offer</h2>

            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
            As a skilled mobile application and website developer, I offer a wide range of services tailored to meet diverse client needs. I specialize in designing and developing custom Android and iOS applications with user-friendly and visually appealing UI/UX designs. My expertise extends to integrating APIs, payment gateways, and third-party services, as well as providing maintenance, optimization, and updates for existing apps. On the website development side, I create responsive and dynamic websites, offer e-commerce solutions with secure payment integrations, and provide CMS development and customization. Additionally, I focus on website maintenance, performance optimization, and SEO services. Leveraging cross-platform frameworks like Flutter, I also provide consultation and prototyping for app and web projects, along with troubleshooting, debugging, and technical support. My goal is to be a one-stop solution for digital transformation and innovation.
            </p>
          </div>

          {/* cards */}
          <div className="md:flex lg:flex gap-10 mx-auto">
            <div className="bg-yellow-400 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={design} alt="design" width={100} height={100} 
              className="inline"
              />
              <h2 className="text-2xl font-bold">
                UI Design
              </h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Crafting intuitive and visually appealing user interfaces that enhance the overall user experience and align with brand identity.</p>
            </div>
          

          
            <div className="bg-yellow-400 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={code} alt="design" width={100} height={100} 
              className="inline"
              />
              <h2 className="text-2xl font-bold">
              App Development
              </h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Building feature-rich and user-friendly mobile applications tailored to client needs for Android and iOS platforms.</p>
            </div>
          

          
            <div className="bg-yellow-400 text-center shadow-sm p-5 rounded-xl my-10">
              <Image src={con} alt="design" width={100} height={100} 
              className="inline"
              />
              <h2 className="text-2xl font-bold">
              Web Development
              </h2>
              <p className="text-sm py-2 text-gray-800 leading-6">Developing responsive, dynamic, and secure websites that deliver seamless user experiences and meet modern industry standards.</p>
            </div>
          </div>
        </section>

        {/* mywork  */}
        <section>
          <div>
            <h2 className="text-4xl py-6 font-bold opacity-60 dark:text-white">
            Portfolio
            </h2>

            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
            I am dedicating software engineer  in mobile application and website development. I am passionate about creating innovative, user-focused solutions that seamlessly blend functionality with aesthetics. With expertise in UI design, app development, and web development, I deliver intuitive user interfaces, feature-rich mobile applications, and responsive, secure websites tailored to diverse client needs. Proficient in modern technologies and frameworks like Flutter, I excel at developing cross-platform solutions, integrating APIs, and optimizing performance. My commitment to quality and staying updated with emerging trends enables me to craft solutions that exceed expectations. Whether designing a dynamic website or building a scalable app, I aim to transform ideas into impactful digital experiences.
            </p>
          </div>

          {/* images */}
          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
            <div className="basic-1/3 flex-1">
            <Image src={auction} alt="auction" layout="responsive" className="rounded-lg object-cover" />
            </div>

            <div className="basic-1/3 flex-1">
            <Image src={lms} alt="lms" layout="responsive" className="rounded-lg object-cover"/>
            </div>

            <div className="basic-1/3 flex-1">
            <Image src={train} alt="train" layout="responsive" className="rounded-lg object-cover"/>
            </div>

            <div className="basic-1/3 flex-1">
            <Image src={cartoon} alt="cartoon" layout="responsive" className="rounded-lg object-cover"/>
            </div>


            <div className="basic-1/3 flex-1">
            <Image src={bus} alt="bus" layout="responsive" className="rounded-lg object-cover"/>
            </div>

            <div className="basic-1/3 flex-1">
            <Image src={minion} alt="minion" layout="responsive" className="rounded-lg object-cover"/>
            </div>

          </div>

          {/* footer */}

          <footer className="border-t-2 border-black text-sm opacity-70 flex-col gap-5 items-center justify-center py-10
                              lg:flex-row lg:items-center dark:text-white">
            <div>
              <h3 className="text-base mb-2 dark:text-white"> contact me for more details</h3>
              <p className="opacity-40 dark:text-white">As a skilled mobile application and website developer, I offer a wide range of services tailored to meet diverse client needs. I specialize in designing and developing custom Android and iOS applications with user-friendly and visually appealing UI/UX designs. My expertise extends to integrating APIs, payment gateways, and third-party services, as well as providing maintenance, optimization, and updates for existing apps. On the website development side, I create responsive and dynamic websites, offer e-commerce solutions with secure payment integrations, and provide CMS development and customization. Additionally, I focus on website maintenance, performance optimization, and SEO services. Leveraging cross-platform frameworks like Flutter, I also provide consultation and prototyping for app and web projects, along with troubleshooting, debugging, and technical support. My goal is to be a one-stop solution for digital transformation and innovation.

              </p>

            </div>
            <div>
              <div className="text-5xl flex justify-center gap-16 text-gray-600 p-10">
              <a href="https://www.instagram.com/sandun.sampath.m/profilecard/?igsh=cDlybWtqeG5zODd3">
                <FaInstagramSquare/>
              </a>

              <a href="https://github.com/Medagangoda">
              <FaGithub/>
              </a>

              <a href="https://www.linkedin.com/in/sandun-sampath/">
              <FaLinkedin/>
              </a>
              </div>
            </div>
          </footer>
        </section>

      </main> 
        
      
    </div>
  );
}
